# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'


use_frameworks!
pod 'Alamofire'
pod 'SwiftyJSON'
# Pods for RestCalls


target 'RestCalls' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks


end
